#!/usr/bin/env python3
"""new_project.py — scaffold a minimal SwiftUI iOS app driven by xcodebuild.

The output is a self-contained Xcode project that builds and runs via the
sibling app/deploy.py with no manual Xcode steps.

Authored by Chase Eddies <source@distillative.ai>.
"""
from __future__ import annotations

import argparse
import re
import sys
import uuid
from pathlib import Path
from textwrap import dedent

PBX_TEMPLATE = """// !$*UTF8*$!
// Minimal pbxproj generated by new_project.py — edit at your peril.
// For real projects use SwiftPM or `xcodegen`.
"""


def slugify(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "", name)
    if not s or not s[0].isalpha():
        s = "App" + s
    return s


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent(content).lstrip())
    print(f"  + {path}")


def scaffold(out: Path, name: str, bundle_id: str) -> None:
    slug = slugify(name)
    src = out / slug
    write(src / f"{slug}App.swift", f"""
        import SwiftUI

        @main
        struct {slug}App: App {{
            var body: some Scene {{
                WindowGroup {{
                    ContentView()
                }}
            }}
        }}
    """)
    write(src / "ContentView.swift", """
        import SwiftUI

        struct ContentView: View {
            var body: some View {
                VStack(spacing: 12) {
                    Image(systemName: "iphone.gen3")
                        .imageScale(.large)
                        .font(.system(size: 64))
                    Text("Hello from Claude Code Cloud")
                        .font(.title2)
                    Text("Deployed via ios-localdeploy")
                        .foregroundStyle(.secondary)
                }
                .padding()
            }
        }
    """)
    write(src / "Info.plist", f"""
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDisplayName</key><string>{name}</string>
            <key>CFBundleIdentifier</key><string>{bundle_id}</string>
            <key>CFBundleName</key><string>{name}</string>
            <key>CFBundleShortVersionString</key><string>1.0</string>
            <key>CFBundleVersion</key><string>1</string>
            <key>UILaunchScreen</key><dict/>
            <key>UIRequiredDeviceCapabilities</key><array><string>arm64</string></array>
        </dict>
        </plist>
    """)
    write(out / "iosdeploy.toml", f"""
        [ios-localdeploy]
        project       = "{slug}.xcodeproj"
        scheme        = "{slug}"
        configuration = "Debug"
        target        = "simulator"
        device        = "iPhone 15"
        bundle_id     = "{bundle_id}"
    """)
    print()
    print("Scaffold complete.")
    print()
    print("Next steps:")
    print(f"  1. Open {out}/{slug}.xcodeproj in Xcode ONCE to let it materialise the project, OR")
    print(f"     run `xcodegen` against a project.yml of your choosing.")
    print(f"  2. python {Path(__file__).parent.parent}/app/deploy.py")
    print()
    print("(This scaffolder writes Swift sources + Info.plist + iosdeploy.toml.")
    print(" For a real .xcodeproj generator, install `xcodegen` or use SwiftPM.)")


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description="Scaffold a minimal SwiftUI iOS app.")
    p.add_argument("name", help="display name of the app, e.g. 'Hello iPhone'")
    p.add_argument("--bundle-id", required=True, help="e.g. com.example.helloiphone")
    p.add_argument("--out", default=".", help="output directory (default: cwd)")
    args = p.parse_args(argv)
    out = Path(args.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    scaffold(out, args.name, args.bundle_id)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
